version: '3.1'

services:

  selenium:
    image: seleniarm/standalone-chromium:latest
    ports:
      - 4444:4444


  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - selenium



